# Star Streams Game Configuration

[window]
width = 1200.0
height = 900.0

[sprites]
sprite_sheet_path = "assets.png"
sprite_scale_factor = 3.0
tile_width = 16
tile_height = 16
sprite_sheet_width = 8
sprite_sheet_height = 8

[enemy_sprites]
enemy_sprite_sheet_path = "enemy.png"
enemy_bg_path = "enemy_bg.png"
enemy_tint_path = "enemy_tint.png"
enemy_tile_width = 32
enemy_tile_height = 32
enemy_sprite_sheet_width = 8
enemy_sprite_sheet_height = 1
enemy_animation_frames = 8

[world]
num_world_decorations = 500
world_width = 3000.0
world_height = 2500.0

[player]
speed = 2.0
health = 100.0

[enemy]
# NOTE: MAX_NUM_ENEMIES can be adjusted based on target hardware.
# Bevy 0.17.2 rendering performance varies with GPU/CPU capabilities.
# For high-end hardware, max_num_enemies can be increased to 100k+
# For mid-range hardware, 20k-50k is recommended
max_num_enemies = 20000
damage = 1.0
spawn_rate_per_second = 10000  # Start with 10k for testing
health = 100.0
spawn_interval = 1.0
speed = 1.0
# Spawn distance range (min, max) in world units
spawn_distance_min = 3000.0
spawn_distance_max = 8000.0

[kd_tree]
refresh_rate = 0.1

[gun]
bullet_spawn_interval = 0.1
bullet_time_secs = 0.5
bullet_speed = 15.0
bullet_damage = 15.0
num_bullets_per_shot = 10

[colors]
# Background color (RGB 0-255)
bg_color = [197, 204, 184]
